version: '3'

services:

  bench:
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    environment:
      - IBD_PEER_ADDRESS=localhost
      - SYNCED_DATA_DIR=/bitcoin/data
      - SYNCED_BITCOIN_REPO_DIR=/bitcoin
      - CODESPEED_URL=http://codespeed:8000
      - CODESPEED_USER=admin
      - CODESPEED_PASSWORD=password
      - CODESPEED_ENVNAME=ccl-bench-hdd-1
      - NO_CAUTION=1  # Can't drop caches from within a container.
      - MAKE_JOBS=5
      - COMPILERS=clang
      - BENCHES_TO_RUN=gitclone,build,ibd,reindex
      # Set minimumchainwork low so that we actually latch out of IBD at low
      # heights.
      - SYNCED_BITCOIND_ARGS=-minimumchainwork=0x00
    volumes:
      - .:/code:ro

      # You may need to change the source of this mount to a directory on your
      # host machine that contains a synced datadir.
      - /data/bitcoin_bench:/bitcoin/data

  codespeed:
    ports:
      - "8000:8000"
    environment:
      TESTING: 1
      DEBUG: 1
      DATABASE_URL: "postgres://codespeed:foobar00@psql:5432/codespeed"
    links:
      - psql

  psql:
    image: postgres:10
    environment:
      POSTGRES_USER: codespeed
      POSTGRES_PASSWORD: foobar00
    volumes:
      - .:/data
