version: '3'

services:

  codespeed:
    build:
      context: ./codespeed
    ports:
      - "8000:8000"
    environment:
      REPOSITORY_BASE_PATH: "/repos"
      DATABASE_URL: "${DATABASE_URL}"
    volumes:
      - ./codespeed:/code

  sqlmigrate:
    image: ruby:2.5
    volumes:
      - .:/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
